<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><UseWPF>true</UseWPF><AssemblyName>LightroomIsSlow</AssemblyName><RootNamespace>LightroomIsSlow.App</RootNamespace></PropertyGroup><ItemGroup><ProjectReference Include="../LightroomIsSlow.Core/LightroomIsSlow.Core.csproj"/><ProjectReference Include="../LightroomIsSlow.Windows/LightroomIsSlow.Windows.csproj"/></ItemGroup></Project>