<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0-windows10.0.19041.0</TargetFramework><OutputType>WinExe</OutputType><UseWPF>true</UseWPF><AssemblyName>LightroomIsSlow</AssemblyName><RootNamespace>LightroomIsSlow.App</RootNamespace></PropertyGroup><ItemGroup><ProjectReference Include="../LightroomIsSlow.Core/LightroomIsSlow.Core.csproj"/><ProjectReference Include="../LightroomIsSlow.Windows/LightroomIsSlow.Windows.csproj"/></ItemGroup></Project>