using LightroomIsSlow.Core.Models;
namespace LightroomIsSlow.Core.Validation;
public static class SyntheticTraceFactory
{
 public static IReadOnlyList<TelemetrySample> Healthy(int n=120)=>Build(n,i=>new(){CpuSystemPercent=35,CpuLightroomPercent=22,MemoryAvailableMb=8192,MemoryPageReadsPerSecond=0,DiskReadLatencyMs=2,DiskWriteLatencyMs=2,DiskQueueDepth=.2,GpuComputePercent=25,NetworkReceiveBytesPerSecond=100000});
 public static IReadOnlyList<TelemetrySample> StoragePressure(int n=120)=>Build(n,i=>new(){CpuSystemPercent=42,CpuLightroomPercent=15,MemoryAvailableMb=8192,MemoryPageReadsPerSecond=0,DiskReadLatencyMs=45,DiskWriteLatencyMs=32,DiskQueueDepth=7,GpuComputePercent=20});
 public static IReadOnlyList<TelemetrySample> MemoryPressure(int n=120)=>Build(n,i=>new(){CpuSystemPercent=55,MemoryAvailableMb=512,MemoryCommitPercent=96,MemoryPageReadsPerSecond=35,DiskReadLatencyMs=4,DiskQueueDepth=.5});
 public static IReadOnlyList<TelemetrySample> CpuBound(int n=120)=>Build(n,i=>new(){CpuSystemPercent=96,CpuLightroomPercent=85,MemoryAvailableMb=12000,MemoryPageReadsPerSecond=0,DiskReadLatencyMs=2,DiskQueueDepth=.2,GpuComputePercent=20});
 public static IReadOnlyList<TelemetrySample> MissingCounters(int n=120)=>Build(n,i=>new(){CpuSystemPercent=40,CpuLightroomPercent=20});
 private static IReadOnlyList<TelemetrySample> Build(int n,Func<int,Seed> f)=>Enumerable.Range(0,n).Select(i=>{var x=f(i);return new TelemetrySample{TimestampUtc=DateTimeOffset.UnixEpoch.AddSeconds(i),SessionId="synthetic",CpuSystemPercent=x.CpuSystemPercent,CpuLightroomPercent=x.CpuLightroomPercent,MemoryAvailableMb=x.MemoryAvailableMb,MemoryCommitPercent=x.MemoryCommitPercent,MemoryPageReadsPerSecond=x.MemoryPageReadsPerSecond,DiskReadLatencyMs=x.DiskReadLatencyMs,DiskWriteLatencyMs=x.DiskWriteLatencyMs,DiskQueueDepth=x.DiskQueueDepth,GpuComputePercent=x.GpuComputePercent,NetworkReceiveBytesPerSecond=x.NetworkReceiveBytesPerSecond};}).ToArray();
 private sealed record Seed{public double? CpuSystemPercent{get;init;}public double? CpuLightroomPercent{get;init;}public double? MemoryAvailableMb{get;init;}public double? MemoryCommitPercent{get;init;}public double? MemoryPageReadsPerSecond{get;init;}public double? DiskReadLatencyMs{get;init;}public double? DiskWriteLatencyMs{get;init;}public double? DiskQueueDepth{get;init;}public double? GpuComputePercent{get;init;}public double? NetworkReceiveBytesPerSecond{get;init;}}
}
